SFDXProject/force-app/main/default/objects/Imoveis__c/Imoveis__c.object-meta.xml
<CustomObject>
    <description>Exibe informações de imóveis</description>
    <label>Imóveis</label>
    <nameField>
        <displayFormat>IMO-{0000}</displayFormat>
        <label>Imóveis Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Imóveis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDXProject/force-app/main/default/objects/Imoveis__c/fields/Banheiro__c.field-meta.xml
<CustomField>
    <fullName>Banheiro__c</fullName>
    <inlineHelpText>Insira quantidade de banheiros</inlineHelpText>
    <label>Banheiro</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFDXProject/force-app/main/default/objects/Imoveis__c/fields/Copas__c.field-meta.xml
<CustomField>
    <fullName>Copas__c</fullName>
    <inlineHelpText>Insira quantidade de copas</inlineHelpText>
    <label>Copas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFDXProject/force-app/main/default/objects/Imoveis__c/fields/Cozinha__c.field-meta.xml
<CustomField>
    <fullName>Cozinha__c</fullName>
    <inlineHelpText>Insira quantidade de cozinhas</inlineHelpText>
    <label>Cozinha</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFDXProject/force-app/main/default/objects/Imoveis__c/fields/Quartos__c.field-meta.xml
<CustomField>
    <fullName>Quartos__c</fullName>
    <inlineHelpText>Insira quantidade de quartos</inlineHelpText>
    <label>Quartos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFDXProject/force-app/main/default/objects/Imoveis__c/fields/Sala__c.field-meta.xml
<CustomField>
    <fullName>Sala__c</fullName>
    <inlineHelpText>Insira quantidade de salas</inlineHelpText>
    <label>Sala</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFDXProject/force-app/main/default/objects/Imoveis__c/fields/TipoImovel__c.field-meta.xml
<CustomField>
    <fullName>TipoImovel__c</fullName>
    <inlineHelpText>Escolha o tipo do imóvel</inlineHelpText>
    <label>Tipo do Imóvel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nenhum</fullName>
                <default>true</default>
                <label>Nenhum</label>
            </value>
            <value>
                <fullName>Casa</fullName>
            </value>
            <value>
                <fullName>Apartamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFDXProject/force-app/main/default/classes/ImobiliariaController.cls
public class ImobiliariaController {
    
    //Definiçoes das variáveis
    
    public integer quartos{get; set;}
    public integer banheiros{get; set;}
    public integer sala{get; set;}
    public integer cozinha{get; set;}
    public integer copas{get; set;}
    public integer valor{get; set;}
    public String tipoImovel{get; set;}
    
    //Método picklist
    public list<SelectOption> getMinhasOpcoes(){
        //Mapear o campo de lista de seleção/picklist que desejo listar
        Schema.DescribeFieldResult describeResult = Imoveis__c.TipoImovel__c.getDescribe();
        
        //listar as opções válidas dentro do meu campo
        List<Schema.PicklistEntry> entries = describeResult.getPicklistValues();
        
        //Cria variável de retorno do tipo de lista para o objeto SelectOption
        List<SelectOption> optionsToReturn = new List <SelectOption>();
        
        //Adiciona as opções do campo listadas
        for(Schema.PicklistEntry pEntry : entries){
            
            //se a opção esta ativa
            //Ou pode aplicar o filtro que quiser, caso não queira mostrar todas as opções
            if(pEntry.isActive()){
                //Adiciona o nome e o valor na variável retorno
                optionsToReturn.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
            }
        }
        return optionsToReturn;
    }
    
    //Método salvar
    public void salvarImoveis(){
        Imoveis__c objImoveis = new Imoveis__c();
        objImoveis.Quartos__C = quartos;
        objImoveis.Banheiro__C = banheiros;
        objImoveis.Sala__C = sala;
        objImoveis.Cozinha__C = cozinha;
        objImoveis.Copas__C = copas;
        objImoveis.Valor__C = valor;
        objImoveis.TipoImovel__c = tipoImovel;
        
        try{
            
            if(objImoveis.TipoImovel__c != 'Nenhum' && objImoveis.TipoImovel__c != null){
                
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.CONFIRM, 'Imóvel cadastrado com sucesso!'));
                insert objImoveis;
                
                //Limpa os campos após salvar
                quartos = null;
                banheiros = null;
                sala = null;
                cozinha = null;
                copas = null;
                valor = null;
                tipoImovel = null;
                
            }else{
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'O campo Tipo do Imóvel deverá ser preenchido!'));
            }
            
        }catch(DmlException e){
            
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'O campo Tipo do Imóvel deverá ser preenchido!'));
            
        }
        
        
        
    }
}